project:
  type: website

website:
  title: "LF5"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: Softwareentwicklung_Vorgehensmodelle.qmd
        text: Vorgehensmodelle in der Softwareentwicklung
      - href: UML_Aktivitätsd-Use-Case-D.qmd
        text: UML Aktivitätsdiagramm, Anwendungsfalldiagramm (= Use Case-Diagramm)

format:
  revealjs:
    include-after-body: libs/backlink.html
    css: libs/styles.css
    logo: libs/_Images/logo-AFBB.svg

publish:
  gh-pages: true
